// Copyright (c) 2018 GitHub, Inc.
// Use of this source code is governed by the MIT license that can be
// found in the LICENSE file.

#ifndef ATOM_COMMON_NATIVE_MODULE_LOADER_H_
#define ATOM_COMMON_NATIVE_MODULE_LOADER_H_

#include "node_native_module.h"  // NOLINT(build/include)

namespace atom {

class NativeModuleLoader : public node::native_module::NativeModuleLoader {
 public:
  NativeModuleLoader();
  virtual ~NativeModuleLoader();

  v8::Local<v8::String> GetSource(v8::Isolate* isolate,
                                  const char* id) const override;

 private:
  // Generated by tools/js2c.py as atom_natives.cc
  void LoadJavaScriptSource();  // Loads data into source_

  node::native_module::NativeModuleRecordMap source_;

  DISALLOW_COPY_AND_ASSIGN(NativeModuleLoader);
};

}  // namespace atom

#endif  // ATOM_COMMON_NATIVE_MODULE_LOADER_H_
